name: Build and Test Pull Requests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: gradle build test

      - name: Merge pull request
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev' && github.event.pull_request.reviews[0].state == 'APPROVED'
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automatically merging pull request'
          title: 'Automatically merging pull request'
          branch: dev
          delete-branch: true

      - name: Merge pull request into main
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev' && github.event.pull_request.reviews[0].state == 'APPROVED'
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automatically merging pull request'
          title: 'Automatically merging pull request'
          branch: main
          delete-branch: true